name:         flumol
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  3D molecules in Flutter!
homepage:     https://github.com/hermanbergwerf/flumol
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  vector_math: ^2.0.4
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/Flumolol.mol
